### ISSUE TITLE
middlewares.parseBodyKeepRaw producing invalid json

### ISSUE THREAD

**Issue by lieutdan13** [clabot/clabot#8]
I'm having an issue where the `middlewares.parseBodyKeepRaw` method is assigning invalid json to the `req.body` variable. In routes.coffee, if I set `payload = JSON.parse req.rawBody`, the app works fine. Is there a reason that the rawBody object isn't being used here?

**Comment by buckett** [comment]
This is the stack trace I see because of this issue:

```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at exports.notify (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/src/lib/routes.js:18:20)
    at callbacks (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/lib/router/index.js:33:10)
    at next (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/clabot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
```

And making the suggested change appears to fix the issue for me.

**Comment by lieutdan13** [comment]
This repository is no longer maintained. Archiving the repository.
